<?php include './include/inner_header.php' ?>
<section class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_5.jpg');" >
   <div class="overlay"></div>
   <div class="container">
      <div class="inner_header">
         <div class="row no-gutters slider-text align-items-end">
            <div class="col-md-6 ftco-animate  breadcurmb_sec">
               <h1 class="mb-0 bread">Cookie Policy</h1>
            </div>
            <div class="col-md-6 ftco-animate text-right breadcurmb_sec">
               <p class="breadcrumbs"><a href="index.php">Home<span class="mx-2"> <i class="ion-ios-arrow-forward"></i></span></a> <span class="mr-2"><a href="cookiepolicy.php">Cookie Policy</a></p>
            </div>
         </div>
      </div>
   </div>
</section>
<section  class="ftco-counter img ftco-section bg-light">
   <div class="container">
      <div class="row">
         <div class="col-lg-12 policy_content">
            

         <h4> What are cookies?</h4>
<p>Cookies are tiny text files that are stored on your computer, tablet or mobile phone. They are NOT
harmful to your computer or your security and despite misconceptions, are nothing to do with viruses
like &#39;Trojans&#39;. When you visit a website, Cookies allow the website to &#39;remember&#39; you and how you’ve
used the website each time you come back, which means you get a much better online experience.</p>

<p>If you want to know more about cookies there is lots of information readily available online.</p>
<h4>What If I Want To Control My Cookie Permissions?</h4>
<p>If you don’t want to receive cookies you can modify your browser so that it notifies you when they are
sent to you, or you can refuse cookies altogether. You can also delete cookies that have already been
set.</p>
<h4>How We Use Cookies</h4>
<p>We use Google Analytics, a web analytics service provided by Google Inc. (Google) which uses cookies to
help analyse how the website is used to improve your experience in our systems.</p><p>
A so-called “User ID” will be used on this website. The User ID functions as your alias in Google Analytics.
Google connects your online behaviour and the User-ID to a profile. Google Analytics tracks your
activities on an anonymised basis across multiple devices (tablet, PC, smartphone, etc.).
</p>
<p>
The information generated by the cookies about your use of the website (including your IP address) will
be transmitted to and stored by Google. Google will use this information for the purpose of evaluating
your use of the website, compiling reports on website activity for us and providing other services
relating to website activity and internet usage. Google may also transfer this information to third parties
where required to do so by law, or where such third parties process the information on Google’s behalf.
Google will not associate your IP address with any other data held by Google.
</p>
<p>
Google only receives the User-ID, not the information contained in the above-mentioned profile or
other personal data of yours. A summarised version of the profile created is accessible to us. We do not
attach any other of your personally identifiable data to the profile connected to a User-ID.
</p>
<p>You may also refuse the use of cookies by selecting the appropriate settings on your browser, however,
please note that if you do this you may not be able to use the full functionality of this website. By using
this website, you consent to the processing of data about you by Google in the manner and for the
purposes set out above.</p>
<p>
Further information about cookies is available at http://www.aboutcookies.org.</p>

   <h4>User Agreement</h4>
 <p>By continuing to use our site, you agree to the placement of cookies on your device. If you choose not to
receive our cookies, we cannot guarantee that your experience will be as fulfilling as it would otherwise
be.</p>
<h4>Contact Us</h4>
            <p>In case of any questions or suggestions about the Privacy Policy, Please feel free to contact MYPLACE.<br>
               Corporate Office & Development Center - India<br>
            </p>
            <p><b>Address: </b>
            My Place 5, Jopling Road,<br>
               Lucknow – 226001 (UP),India<br>
               <b>Email:</b>
               info@myplacecoworking.com
            </p>




         </div>
      </div>
   </div>
</section>
<?php include './include/footer.php' ?>